vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
         publication_images:
            uri_prefix: /images/publication
            upload_destination: '%kernel.project_dir%/public/images/publication'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
